import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ToasterProvider from "providers/ToastProvider";
import { SessionProvider } from "next-auth/react";
import { auth } from "auth";
import getCurrentUser from "actions/getCurrentUser";
import { useCurrentUser } from "hooks/use-current-user";
import { getUserByEmail } from "data/user";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Assessment",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <ToasterProvider />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
